basic.showIcon(IconNames.Happy)
basic.showIcon(IconNames.Silly)
basic.showIcon(IconNames.Surprised)
basic.showIcon(IconNames.Fabulous)
basic.showIcon(IconNames.Happy)
basic.clearScreen()
basic.showString("EDU:BIT CLASS")
basic.forever(function () {
    basic.showString("16 MAY 2020 :")
    basic.showString("NO HOMEWORK")
})
